# Generated by Django 3.1.2 on 2021-01-20 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rechnung_strasse', models.CharField(max_length=255)),
                ('rechnung_nr', models.CharField(max_length=255)),
                ('rechnung_ort', models.CharField(max_length=255)),
                ('rechnung_land', django_countries.fields.CountryField(max_length=2)),
                ('rechnung_plz', models.CharField(max_length=255)),
                ('address_type', models.CharField(choices=[('B', 'Rechnungsadresse'), ('S', 'Lieferadresse')], max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rechnungsadresse',
                'verbose_name_plural': 'Rechnungsadressen',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('categorypic', models.ImageField(blank=True, null=True, upload_to='produktbilder/')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DichtungMasse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aussenbreite', models.IntegerField(blank=True, null=True)),
                ('aussenhöhe', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Dichtung Masse',
                'verbose_name_plural': 'Dichtung Masse',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=255)),
                ('preis', models.FloatField()),
                ('preis2', models.FloatField(blank=True, null=True)),
                ('preis3', models.FloatField(blank=True, null=True)),
                ('kurzbeschreibung', models.CharField(default='', max_length=500)),
                ('beschreibung', models.CharField(default='', max_length=500)),
                ('lieferung', models.CharField(blank=True, max_length=255, null=True)),
                ('montage', models.CharField(blank=True, max_length=255, null=True)),
                ('titelbild', models.ImageField(blank=True, null=True, upload_to='produktbilder/')),
                ('slug', models.SlugField(max_length=255)),
                ('artikelnr', models.IntegerField()),
                ('farbe', models.CharField(max_length=255)),
                ('kategorie', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category')),
            ],
            options={
                'verbose_name': 'Produkte',
                'verbose_name_plural': 'Produkte',
            },
        ),
        migrations.CreateModel(
            name='ShippingCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_from', models.FloatField(blank=True, null=True)),
                ('price_to', models.FloatField(blank=True, null=True)),
                ('shipping_price', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('aussenbreite', models.IntegerField(blank=True, default=250, null=True)),
                ('aussenhöhe', models.IntegerField(blank=True, default=250, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('payment', models.BooleanField(default=False)),
                ('payment_method', models.CharField(choices=[('R', 'Rechnung*'), ('V', 'Vorkasse (2% Skonto)')], default='R', max_length=255)),
                ('shippingcost', models.FloatField(blank=True, default=0, null=True)),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_address', to='store.address')),
                ('items', models.ManyToManyField(to='store.OrderItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bestellung',
                'verbose_name_plural': 'Bestellungen',
            },
        ),
        migrations.CreateModel(
            name='Kunde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firmenname', models.CharField(max_length=255)),
                ('rabatt', models.FloatField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kunde',
                'verbose_name_plural': 'Kunden',
            },
        ),
        migrations.CreateModel(
            name='Elemente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elementnr', models.IntegerField(blank=True, null=True)),
                ('kuehlposition', models.CharField(max_length=255)),
                ('bemerkung', models.CharField(max_length=255)),
                ('dichtung_masse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.dichtungmasse')),
                ('dichtungen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.item')),
                ('kunde', models.ManyToManyField(to='store.Kunde')),
            ],
            options={
                'verbose_name': 'Element',
                'verbose_name_plural': 'Elemente',
            },
        ),
        migrations.AddField(
            model_name='dichtungmasse',
            name='dichtungen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.item'),
        ),
    ]
