# Generated by Django 4.1.4 on 2025-03-22 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementecartitem',
            name='comment',
        ),
    ]
