# Generated by Django 3.1.2 on 2021-01-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kunde',
            name='newsletter',
            field=models.BooleanField(default=False),
        ),
    ]
