# Generated by Django 4.1.4 on 2025-04-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kunde',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
