# Generated by Django 4.1.4 on 2025-03-24 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementecartitem',
            name='element_nr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elemente_cart_items', to='store.elemente'),
        ),
    ]
