# Generated by Django 5.1.6 on 2025-03-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_bezeichnung_alter_elemente_bezeichnung'),
    ]

    operations = [
        migrations.AddField(
            model_name='kunde',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
