# Generated by Django 4.1.4 on 2025-03-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_elementecartitem_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementecartitem',
            name='element_nr',
        ),
        migrations.AddField(
            model_name='elementecartitem',
            name='elemente_nr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
