# Generated by Django 3.1.2 on 2021-01-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_kunde_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kunde',
            name='newsletter',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
