# Generated by Django 4.1.4 on 2025-03-22 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_elementecartitem_element_nr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elementecartitem',
            old_name='elemente_nr',
            new_name='element_nr',
        ),
    ]
