# Generated by Django 4.1.4 on 2025-04-01 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_bezeichnung'),
    ]

    operations = [
        migrations.AddField(
            model_name='elemente',
            name='bezeichnung_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elemente_bezeichnung', to='store.bezeichnung'),
        ),
    ]
