# Generated by Django 3.1.2 on 2021-01-22 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_auto_20210121_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieferung_strasse', models.CharField(max_length=255)),
                ('lieferung_nr', models.CharField(max_length=255)),
                ('lieferung_ort', models.CharField(max_length=255)),
                ('lieferung_land', django_countries.fields.CountryField(max_length=2)),
                ('lieferung_plz', models.CharField(max_length=255)),
                ('address_type', models.CharField(choices=[('B', 'Rechnungsadresse'), ('S', 'Lieferadresse')], max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lieferadresse',
                'verbose_name_plural': 'Lieferadressen',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_address', to='store.shippingaddress'),
        ),
    ]
