# Generated by Django 3.1.2 on 2021-01-22 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210122_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='address_type',
        ),
    ]
