# Generated by Django 4.1.4 on 2025-03-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_elemente_nr_elementecartitem_element_nr'),
    ]

    operations = [
        migrations.AddField(
            model_name='elemente_bestellungen',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
