# Generated by Django 3.1.2 on 2021-01-22 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_shippingaddress_address_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_type',
        ),
    ]
