# Generated by Django 4.1.4 on 2025-04-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_elemente_bezeichnung_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmaddress',
            name='crm_kanton',
            field=models.CharField(blank=True, choices=[('Aargau', 'Aargau'), ('Appenzell Innerrhoden', 'Appenzell Innerrhoden'), ('Appenzell Ausserrhoden', 'Appenzell Ausserrhoden'), ('Bern', 'Bern'), ('Basel-Landschaft', 'Basel-Landschaft'), ('Basel-Stadt', 'Basel-Stadt'), ('Freiburg', 'Freiburg'), ('Genf', 'Genf'), ('Glarus', 'Glarus'), ('Graubünden', 'Graubünden'), ('Jura', 'Jura'), ('Luzern', 'Luzern'), ('Neuenburg', 'Neuenburg'), ('Nidwalden', 'Nidwalden'), ('Obwalden', 'Obwalden'), ('St. Gallen', 'St. Gallen'), ('Schaffhausen', 'Schaffhausen'), ('Solothurn', 'Solothurn'), ('Schwyz', 'Schwyz'), ('Thurgau', 'Thurgau'), ('Tessin', 'Tessin'), ('Uri', 'Uri'), ('Waadt', 'Waadt'), ('Wallis', 'Wallis'), ('Zug', 'Zug'), ('Zürich', 'Zürich')], default='', max_length=255, null=True),
        ),
    ]
