# Generated by Django 4.1.4 on 2025-03-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_elemente_bestellungen_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemente_bestellungen',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kommentar'),
        ),
    ]
