# Generated by Django 3.1.2 on 2021-01-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_address_address_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('B', 'Rechnungsadresse'), ('S', 'Lieferadresse')], default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='address_type',
            field=models.CharField(choices=[('B', 'Rechnungsadresse'), ('S', 'Lieferadresse')], default=1, max_length=500),
            preserve_default=False,
        ),
    ]
