# Generated by Django 5.1.6 on 2025-04-16 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_elemente_bestellungen_notizfeld'),
    ]

    operations = [
        migrations.AddField(
            model_name='elemente_bestellungen',
            name='kunde',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.kunde'),
        ),
    ]