# Generated by Django 4.1.4 on 2025-04-17 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_elemente_bestellungen_notizfeld'),
    ]

    operations = [
        migrations.AddField(
            model_name='elemente_bestellungen',
            name='kunde',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.kunde'),
        ),
    ]
