# Generated by Django 3.1.2 on 2021-01-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_pct',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
