# Generated by Django 4.1.4 on 2025-04-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_elemente_bestellungen_kunde'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elemente_bestellungen',
            name='kunde',
        ),
        migrations.AddField(
            model_name='elemente_bestellungen',
            name='wer',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Zuständigkeit'),
        ),
        migrations.AlterField(
            model_name='elemente_bestellungen',
            name='status',
            field=models.CharField(choices=[('offen', 'offen'), ('bestellt', 'bestellt'), ('bei Lieferant', 'bei Lieferant'), ('erledigt', 'erledigt')], default='offen', max_length=20, verbose_name='Status'),
        ),
    ]
