# Generated by Django 4.1.4 on 2025-04-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_elemente_bestellungen_kunde_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemente_bestellungen',
            name='wer',
            field=models.CharField(blank=True, choices=[('lager', 'Lager'), ('lieferant', 'Lieferant'), ('produktion', 'Produktion')], default='lager', max_length=50, null=True, verbose_name='Zuständigkeit'),
        ),
    ]
