# Generated by Django 5.1.6 on 2025-05-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_elemente_bestellungen_wer'),
    ]

    operations = [
        migrations.AddField(
            model_name='marke',
            name='bestseller',
            field=models.BooleanField(default=False),
        ),
    ]
