# Generated by Django 3.1.2 on 2021-01-25 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20210125_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='subkategorie',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.subcategory'),
        ),
    ]
