# Generated by Django 3.1.2 on 2021-01-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20210125_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='preis4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='preis5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='preis6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='preis7',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
