# Generated by Django 4.1.4 on 2025-05-02 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_elementecartitem_element_nr'),
    ]

    operations = [
        migrations.AddField(
            model_name='lieferantenbestellungen',
            name='auftrag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auftrag', to='store.elemente_bestellungen'),
        ),
    ]
