# Generated by Django 4.1.4 on 2024-08-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_objekt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objekt',
            name='element',
        ),
        migrations.AddField(
            model_name='objekt',
            name='objekte',
            field=models.ManyToManyField(blank=True, related_name='elemente_objekte', to='store.elemente'),
        ),
    ]
