# Generated by Django 4.1.4 on 2025-06-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_lieferantenbestellungen_auftrag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-artikelnr'], 'verbose_name': 'Produkte', 'verbose_name_plural': 'Produkte'},
        ),
        migrations.AlterField(
            model_name='elemente_bestellungen',
            name='status',
            field=models.CharField(default='offen', max_length=20, verbose_name='Status'),
        ),
    ]
