# Generated by Django 4.1.4 on 2024-08-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_remove_objekt_element_objekt_objekte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objekt',
            name='objekte',
            field=models.ManyToManyField(blank=True, null=True, related_name='elemente_objekte', to='store.elemente'),
        ),
    ]
