# Generated by Django 3.1.2 on 2021-02-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20210125_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='artikelnr',
            field=models.CharField(max_length=255),
        ),
    ]
