# Generated by Django 4.1.4 on 2024-08-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_objekt_objekte'),
    ]

    operations = [
        migrations.AddField(
            model_name='objekt',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
