# Generated by Django 3.1.2 on 2021-02-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20210203_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='falzluft',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='nut',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
