# Generated by Django 4.1.4 on 2025-06-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_marke_bestseller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marke',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='marke',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
