# Generated by Django 3.1.2 on 2021-02-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20210203_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='falz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='fuge',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='glasdicke',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
