# Generated by Django 4.1.4 on 2024-08-26 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_objekt_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Objekt',
            new_name='Objekte',
        ),
    ]
