# Generated by Django 4.1.4 on 2025-06-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_marke_name_alter_marke_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marke',
            options={'ordering': ['name'], 'verbose_name': 'Marke', 'verbose_name_plural': 'Marken'},
        ),
        migrations.AddField(
            model_name='kunde',
            name='customer_type',
            field=models.CharField(choices=[('privat', 'Privatkunde'), ('geschaeft', 'Geschäftskunde'), ('wieder', 'Wiederverkäufer')], default='privat', max_length=10),
        ),
        migrations.AddField(
            model_name='kunde',
            name='hr_auszug',
            field=models.FileField(blank=True, null=True, upload_to='hr_auszuege/'),
        ),
    ]
