# Generated by Django 3.1.2 on 2021-02-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20210203_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='material',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
