# Generated by Django 4.1.4 on 2024-09-13 16:27

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_rename_objekt_objekte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objekte',
            name='objekte',
            field=models.ManyToManyField(blank=True, related_name='elemente_objekte', to='store.elemente'),
        ),
        migrations.CreateModel(
            name='CRMAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_strasse', models.CharField(max_length=255)),
                ('crm_nr', models.CharField(max_length=255)),
                ('crm_ort', models.CharField(max_length=255)),
                ('crm_land', django_countries.fields.CountryField(max_length=2)),
                ('crm_plz', models.CharField(max_length=255)),
                ('address_type', models.CharField(choices=[('B', 'Rechnungsadresse'), ('S', 'Lieferadresse')], max_length=500)),
                ('kunde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kunde_address', to='store.kunde')),
            ],
            options={
                'verbose_name': 'Rechnungsadresse',
                'verbose_name_plural': 'Rechnungsadressen',
            },
        ),
    ]
