# Generated by Django 3.1.2 on 2021-02-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_item_material'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['sub_name'], 'verbose_name': 'Subkategorie', 'verbose_name_plural': 'Subkategorien'},
        ),
        migrations.AddField(
            model_name='item',
            name='hersteller',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='lieferung',
            field=models.CharField(blank=True, default='ca. 5 bis 7 Tage', max_length=255, null=True),
        ),
    ]
