# Generated by Django 4.1.4 on 2024-09-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_crmaddress_options_kunde_email_kunde_kanton_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kunde',
            name='kanton',
        ),
        migrations.AddField(
            model_name='crmaddress',
            name='crm_kanton',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
