# Generated by Django 3.1.2 on 2021-02-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20210203_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='farbe',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
