# Generated by Django 3.1.2 on 2021-02-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20210203_1251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['sortierung'], 'verbose_name': 'Produkte', 'verbose_name_plural': 'Produkte'},
        ),
        migrations.AddField(
            model_name='item',
            name='sortierung',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
