# Generated by Django 4.1.4 on 2024-09-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_remove_kunde_kanton_crmaddress_crm_kanton'),
    ]

    operations = [
        migrations.AddField(
            model_name='kunde',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
