# Generated by Django 4.1.4 on 2024-09-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_kunde_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketplace',
            name='category',
        ),
        migrations.RemoveField(
            model_name='marketplace',
            name='user',
        ),
        migrations.AddField(
            model_name='kunde',
            name='last_service',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='JobsMarketplace',
        ),
        migrations.DeleteModel(
            name='Marketplace',
        ),
        migrations.DeleteModel(
            name='MP_Category',
        ),
        migrations.DeleteModel(
            name='MP_JobsCategory',
        ),
    ]
