# Generated by Django 3.1.2 on 2021-02-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_auto_20210213_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sortierung',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
    ]
