# Generated by Django 3.1.2 on 2021-02-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_auto_20210213_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='firmenname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='nachname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='vorname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='sortierung',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
