# Generated by Django 3.1.2 on 2021-02-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_auto_20210222_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='kunde',
            name='birthday',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kunde',
            name='mobile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kunde',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kunde',
            name='firmenname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
