# Generated by Django 3.1.2 on 2021-03-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_auto_20210222_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elemente',
            name='dichtung_masse',
        ),
        migrations.AddField(
            model_name='elemente',
            name='aussenbreite',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='elemente',
            name='aussenhöhe',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='DichtungMasse',
        ),
    ]
