# Generated by Django 4.1.4 on 2024-09-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_alter_kunde_last_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='kunde',
            name='zusatz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
