# Generated by Django 3.1.2 on 2021-04-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_auto_20210312_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kunde',
            options={'ordering': ['id'], 'verbose_name': 'Kunde', 'verbose_name_plural': 'Kunden'},
        ),
        migrations.AddField(
            model_name='orderitem',
            name='element',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='elemente',
            name='kunde',
            field=models.ManyToManyField(blank=True, related_name='kunden_elemente', to='store.Kunde'),
        ),
    ]
