# Generated by Django 4.1.4 on 2024-09-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_kunde_zusatz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmaddress',
            name='address_type',
            field=models.CharField(blank=True, choices=[('B', 'Rechnungsadresse'), ('S', 'Lieferadresse')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='crmaddress',
            name='crm_kanton',
            field=models.CharField(blank=True, choices=[('Aargau', 'Aargau'), ('Appenzell Innerrhoden', 'Appenzell Innerrhoden'), ('Appenzell Ausserrhoden', 'Appenzell Ausserrhoden'), ('Bern', 'Bern'), ('Basel-Landschaft', 'Basel-Landschaft'), ('Basel-Stadt', 'Basel-Stadt'), ('Freiburg', 'Freiburg'), ('Genf', 'Genf'), ('Glarus', 'Glarus'), ('Graubünden', 'Graubünden'), ('Jura', 'Jura'), ('Luzern', 'Luzern'), ('Neuenburg', 'Neuenburg'), ('Nidwalden', 'Nidwalden'), ('Obwalden', 'Obwalden'), ('St. Gallen', 'St. Gallen'), ('Schaffhausen', 'Schaffhausen'), ('Solothurn', 'Solothurn'), ('Schwyz', 'Schwyz'), ('Thurgau', 'Thurgau'), ('Tessin', 'Tessin'), ('Uri', 'Uri'), ('Waadt', 'Waadt'), ('Wallis', 'Wallis'), ('Zug', 'Zug'), ('Zürich', 'Zürich')], default='Zürich', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='crmaddress',
            name='crm_nr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='crmaddress',
            name='crm_ort',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='crmaddress',
            name='crm_plz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='crmaddress',
            name='crm_strasse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
