# Generated by Django 4.1.4 on 2023-01-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_auto_20210421_1322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elemente',
            options={'ordering': ['elementnr'], 'verbose_name': 'Element', 'verbose_name_plural': 'Elemente'},
        ),
        migrations.AddField(
            model_name='kunde',
            name='interne_nummer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
