# Generated by Django 4.1.4 on 2024-09-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_alter_crmaddress_address_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elemente',
            name='produkt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
