# Generated by Django 4.1.4 on 2023-01-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_marke_item_marke'),
    ]

    operations = [
        migrations.AddField(
            model_name='marke',
            name='markepic',
            field=models.ImageField(blank=True, null=True, upload_to='markebilder/'),
        ),
        migrations.AddField(
            model_name='marke',
            name='marketext',
            field=models.TextField(blank=True),
        ),
    ]
