# Generated by Django 4.1.4 on 2024-10-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_elemente_produkt'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMLager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(blank=True, max_length=255, null=True)),
                ('aussenbreite', models.IntegerField(blank=True, default=250, null=True)),
                ('aussenhöhe', models.IntegerField(blank=True, default=250, null=True)),
                ('dichtungstyp', models.CharField(blank=True, max_length=255, null=True)),
                ('lagerort', models.CharField(blank=True, max_length=255, null=True)),
                ('lagerbestand', models.IntegerField(blank=True, default=250, null=True)),
                ('marke', models.ManyToManyField(blank=True, related_name='lager_marke', to='store.marke')),
            ],
            options={
                'verbose_name': 'CRM-Lager',
                'verbose_name_plural': 'CRM-Lagerbestände',
            },
        ),
    ]
