# Generated by Django 4.1.4 on 2024-10-03 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_crmlager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmlager',
            name='aussenbreite',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crmlager',
            name='aussenhöhe',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crmlager',
            name='lagerbestand',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.RemoveField(
            model_name='crmlager',
            name='marke',
        ),
        migrations.AddField(
            model_name='crmlager',
            name='marke',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lager_marke', to='store.marke'),
        ),
    ]
