# Generated by Django 4.1.4 on 2023-01-20 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_marke_markepic_marke_marketext'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('price', models.FloatField(blank=True, null=True)),
                ('description', models.CharField(default='', max_length=500)),
                ('condition', models.CharField(choices=[('G', 'Gebraucht'), ('N', 'Neu')], default='G', max_length=255)),
                ('place', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='inserate/')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='inserate/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='inserate/')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Marketplace',
                'verbose_name_plural': 'Marketplaces',
                'ordering': ['add_date'],
            },
        ),
        migrations.CreateModel(
            name='MP_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
            ],
            options={
                'verbose_name': 'MP_Kategorie',
                'verbose_name_plural': 'MP_Kategorien',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='item',
            name='marke',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_marke', to='store.marke'),
        ),
    ]
