# Generated by Django 4.1.4 on 2024-10-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_alter_crmlager_aussenbreite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elemente',
            name='nettopreis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='elemente',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
