# Generated by Django 4.1.4 on 2023-01-20 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_marketplace_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplace',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mp_category', to='store.mp_category'),
        ),
    ]
