# Generated by Django 4.1.4 on 2024-10-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_elemente_nettopreis_elemente_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lieferanten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('plz', models.CharField(blank=True, max_length=255, null=True)),
                ('ort', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Lieferant',
                'verbose_name_plural': 'Lieferanten',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='elemente',
            name='nettopreis',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='elemente',
            name='number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
