# Generated by Django 4.1.4 on 2023-01-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_marketplace_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplace',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
