# Generated by Django 4.1.4 on 2024-10-18 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_objekte_lieferant'),
    ]

    operations = [
        migrations.AddField(
            model_name='elemente',
            name='lieferant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elemente_lieferanten', to='store.lieferanten'),
        ),
    ]
