# Generated by Django 4.1.4 on 2023-01-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_marketplace_tid'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplace',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
