# Generated by Django 4.1.4 on 2024-11-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_lieferanten_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artikelnr', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('aussenbreite', models.IntegerField(blank=True, null=True)),
                ('aussenhöhe', models.IntegerField(blank=True, null=True)),
                ('nettopreis', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Artikel',
                'verbose_name_plural': 'Artikel',
                'ordering': ['id'],
            },
        ),
    ]
