# Generated by Django 4.1.4 on 2023-02-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_marketplace_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-ordered_date'], 'verbose_name': 'Bestellung', 'verbose_name_plural': 'Bestellungen'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='marke',
        ),
        migrations.AddField(
            model_name='item',
            name='marke',
            field=models.ManyToManyField(to='store.marke'),
        ),
    ]
