# Generated by Django 4.1.4 on 2024-11-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_artikel'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='elemente',
            field=models.ManyToManyField(blank=True, related_name='artikel_elemente', to='store.elemente'),
        ),
    ]
