# Generated by Django 4.1.4 on 2023-02-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_alter_order_options_remove_item_marke_item_marke'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='marke',
        ),
        migrations.AddField(
            model_name='marke',
            name='item',
            field=models.ManyToManyField(blank=True, related_name='item_marken', to='store.item'),
        ),
    ]
