# Generated by Django 4.1.4 on 2024-11-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_artikel_elemente'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='vp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='nettopreis',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
