# Generated by Django 4.1.4 on 2024-11-29 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_artikel_vp_alter_artikel_nettopreis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artikel',
            name='elemente',
        ),
        migrations.AddField(
            model_name='artikel',
            name='elemente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artikel_elemente', to='store.elemente'),
        ),
    ]
