# Generated by Django 4.1.4 on 2023-02-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_marketplace_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplace',
            name='numberof',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
