# Generated by Django 4.1.4 on 2024-11-29 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_remove_artikel_elemente_artikel_elemente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artikel',
            name='elemente',
        ),
        migrations.AddField(
            model_name='elemente',
            name='elemente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artikel_elemente', to='store.artikel'),
        ),
    ]
