# Generated by Django 4.1.4 on 2024-11-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_elemente_bestellungen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elemente_bestellungen',
            options={'ordering': ['id'], 'verbose_name': 'Elemente Bestellung', 'verbose_name_plural': 'Elemente Bestellungen'},
        ),
        migrations.AddField(
            model_name='elemente_bestellungen',
            name='ort',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
