# Generated by Django 4.1.4 on 2024-11-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_alter_elemente_bestellungen_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elemente_bestellungen',
            name='lieferant_ausgeloest',
            field=models.BooleanField(default=False, verbose_name='Lieferant Ausgelöst'),
        ),
        migrations.AddField(
            model_name='elemente_bestellungen',
            name='lieferant_date',
            field=models.DateField(blank=True, null=True, verbose_name='Lieferant Datum'),
        ),
    ]
