# Generated by Django 4.1.4 on 2024-12-07 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_elemente_bestellungen_lieferant_ausgeloest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemente',
            name='artikel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artikel_elemente', to='store.artikel'),
        ),
        migrations.AlterField(
            model_name='elemente',
            name='lieferant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elemente_lieferanten', to='store.lieferanten'),
        ),
    ]
