# Generated by Django 4.1.4 on 2024-12-07 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0048_alter_elemente_artikel_alter_elemente_lieferant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preiscode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preiscode', models.CharField(max_length=255, unique=True)),
                ('faktor', models.FloatField(blank=True, null=True)),
                ('transportkosten', models.IntegerField(blank=True, null=True)),
                ('rabatt', models.IntegerField(blank=True, null=True)),
                ('preisanpassung', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Preiscode',
                'verbose_name_plural': 'Preiscodes',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='artikel',
            name='lieferant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artikel_lieferanten', to='store.lieferanten'),
        ),
        migrations.AddField(
            model_name='artikel',
            name='zubehoerartikelnr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='artikelnr',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
