# Generated by Django 4.1.4 on 2024-12-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0049_preiscode_artikel_lieferant_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artikel',
            options={'ordering': ['artikelnr'], 'verbose_name': 'Artikel', 'verbose_name_plural': 'Artikel'},
        ),
        migrations.AddField(
            model_name='artikel',
            name='lagerbestand',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
