# Generated by Django 4.1.4 on 2024-12-11 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0050_alter_artikel_options_artikel_lagerbestand'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='preiscode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artikel_preiscode', to='store.preiscode'),
        ),
    ]
