# Generated by Django 4.1.4 on 2024-12-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0052_artikel_bestpreis_artikel_bestpreis_lieferant'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='lieferantenartikel',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
