# Generated by Django 4.1.4 on 2024-12-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0055_artikel_lagerort'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artikel',
            options={'ordering': ['-artikelnr'], 'verbose_name': 'Artikel', 'verbose_name_plural': 'Artikel'},
        ),
        migrations.AlterField(
            model_name='artikel',
            name='artikelnr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
