# Generated by Django 4.1.4 on 2024-12-11 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0056_alter_artikel_options_alter_artikel_artikelnr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artikel',
            options={'ordering': ['id'], 'verbose_name': 'Artikel', 'verbose_name_plural': 'Artikel'},
        ),
        migrations.RenameField(
            model_name='artikel',
            old_name='bestpreis',
            new_name='vp',
        ),
        migrations.RemoveField(
            model_name='artikel',
            name='bestpreis_lieferant',
        ),
        migrations.RemoveField(
            model_name='artikel',
            name='lagerbestand',
        ),
        migrations.RemoveField(
            model_name='artikel',
            name='lagerort',
        ),
        migrations.RemoveField(
            model_name='artikel',
            name='lieferant',
        ),
        migrations.RemoveField(
            model_name='artikel',
            name='lieferantenartikel',
        ),
        migrations.RemoveField(
            model_name='artikel',
            name='preiscode',
        ),
        migrations.RemoveField(
            model_name='artikel',
            name='zubehoerartikelnr',
        ),
        migrations.DeleteModel(
            name='Preiscode',
        ),
    ]
