# Generated by Django 4.1.4 on 2024-12-11 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0057_alter_artikel_options_rename_bestpreis_artikel_vp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preiscode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preiscode', models.CharField(max_length=255, unique=True)),
                ('faktor', models.FloatField(blank=True, null=True)),
                ('transportkosten', models.IntegerField(blank=True, null=True)),
                ('rabatt', models.IntegerField(blank=True, null=True)),
                ('preisanpassung', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Preiscode',
                'verbose_name_plural': 'Preiscodes',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='artikel',
            options={'ordering': ['-artikelnr'], 'verbose_name': 'Artikel', 'verbose_name_plural': 'Artikel'},
        ),
        migrations.RenameField(
            model_name='artikel',
            old_name='vp',
            new_name='bestpreis',
        ),
        migrations.AddField(
            model_name='artikel',
            name='bestpreis_lieferant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artikel_lieferanten_bestpreis', to='store.lieferanten'),
        ),
        migrations.AddField(
            model_name='artikel',
            name='lagerbestand',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='artikel',
            name='lagerort',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artikel',
            name='lieferant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artikel_lieferanten', to='store.lieferanten'),
        ),
        migrations.AddField(
            model_name='artikel',
            name='lieferantenartikel',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='artikel',
            name='zubehoerartikelnr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artikel',
            name='preiscode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artikel_preiscode', to='store.preiscode'),
        ),
    ]
