# Generated by Django 4.1.4 on 2024-12-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0058_preiscode_alter_artikel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='artikelnr',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
