# Generated by Django 4.1.4 on 2025-01-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0059_alter_artikel_artikelnr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preiscode',
            options={'ordering': ['-preiscode'], 'verbose_name': 'Preiscode', 'verbose_name_plural': 'Preiscodes'},
        ),
        migrations.AddField(
            model_name='elemente',
            name='bezeichnung',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
