# Generated by Django 4.1.4 on 2025-01-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0060_alter_preiscode_options_elemente_bezeichnung'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preiscode',
            options={'ordering': ['preiscode'], 'verbose_name': 'Preiscode', 'verbose_name_plural': 'Preiscodes'},
        ),
        migrations.AlterField(
            model_name='elemente',
            name='bemerkung',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
