# Generated by Django 4.1.4 on 2025-01-25 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0061_alter_preiscode_options_alter_elemente_bemerkung'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementeCartOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kunden_nr', models.CharField(max_length=100, verbose_name='Kunden-Nr.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='artikel',
            options={'verbose_name': 'Artikel', 'verbose_name_plural': 'Artikel'},
        ),
        migrations.CreateModel(
            name='ElementeCartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_nr', models.CharField(max_length=100, verbose_name='Element-Nr.')),
                ('anzahl', models.PositiveIntegerField(verbose_name='Anzahl')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.elementecartorder')),
            ],
        ),
    ]
