# Generated by Django 4.1.4 on 2025-01-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0062_elementecartorder_alter_artikel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementecartorder',
            name='status',
            field=models.CharField(choices=[('offen', 'Offen'), ('abgeschlossen', 'Abgeschlossen')], default='offen', max_length=20, verbose_name='Bestellstatus'),
        ),
    ]
