# Generated by Django 4.1.4 on 2025-01-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0063_elementecartorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementecartorder',
            name='status',
            field=models.CharField(choices=[('warenkorb', 'In den Warenkorb'), ('nicht_bestellt', 'Nicht bestellt'), ('bestellt', 'Bestellt')], default='warenkorb', max_length=20, verbose_name='Bestellstatus'),
        ),
    ]
