# Generated by Django 4.1.4 on 2025-02-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0064_alter_elementecartorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='elemente_bestellungen',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
