# Generated by Django 4.1.4 on 2025-02-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0066_alter_elementecartitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='elemente_bestellungen',
            name='status',
            field=models.CharField(choices=[('offen', 'offen'), ('bestellt', 'bestellt'), ('erledigt', 'erledigt')], default='offen', max_length=20, verbose_name='Status'),
        ),
    ]
