# Generated by Django 4.1.4 on 2025-02-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0068_alter_elementecartitem_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elemente_bestellungen',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='elemente_bestellungen',
            name='bemerkung',
        ),
        migrations.RemoveField(
            model_name='elemente_bestellungen',
            name='betrieb_person',
        ),
        migrations.RemoveField(
            model_name='elemente_bestellungen',
            name='elemente_nr',
        ),
        migrations.RemoveField(
            model_name='elemente_bestellungen',
            name='lieferant_ausgeloest',
        ),
        migrations.RemoveField(
            model_name='elemente_bestellungen',
            name='lieferant_date',
        ),
        migrations.RemoveField(
            model_name='elemente_bestellungen',
            name='lieferschein_pdf',
        ),
        migrations.RemoveField(
            model_name='elemente_bestellungen',
            name='ort',
        ),
        migrations.RemoveField(
            model_name='elemente_bestellungen',
            name='plz',
        ),
        migrations.AlterField(
            model_name='elemente_bestellungen',
            name='status',
            field=models.CharField(choices=[('offen', 'offen'), ('bestellt', 'bestellt'), ('bei Lieferant', 'bei Lieferant'), ('erledigt', 'erledigt')], default='offen', max_length=20, verbose_name='Status'),
        ),
    ]
