# Generated by Django 4.1.4 on 2025-02-10 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0070_lieferantenbestellungen_lieferantenstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lieferantenbestellungen',
            name='lieferant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lieferanten_id', to='store.lieferanten'),
            preserve_default=False,
        ),
    ]
