# Generated by Django 4.1.4 on 2025-02-10 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0071_lieferantenbestellungen_lieferant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lieferantenbestellungen',
            name='lieferant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lieferanten_id', to='store.lieferanten'),
        ),
        migrations.AlterField(
            model_name='lieferantenbestellungen',
            name='status',
            field=models.ManyToManyField(blank=True, related_name='bestellungen_status', to='store.lieferantenstatus'),
        ),
        migrations.AlterField(
            model_name='lieferantenstatus',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
