# Generated by Django 4.1.4 on 2025-02-18 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0072_alter_lieferantenbestellungen_lieferant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elemente_bestellungen',
            name='artikel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elementebestellung_artikel', to='store.artikel'),
        ),
    ]
