# Generated by Django 5.1.6 on 2025-02-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0075_alter_address_id_alter_artikel_id_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementecartitem',
            name='element_nr',
            field=models.CharField(max_length=100, verbose_name='Element-Nr.'),
        ),
    ]
