# Generated by Django 4.1.4 on 2025-03-21 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0075_alter_address_id_alter_artikel_id_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='dichtungstypen',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artikel',
            name='lieferanten_artikelnummern',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='elementecartitem',
            name='element_nr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elemente_cart_items', to='store.elemente'),
        ),
    ]
