# Generated by Django 5.1.6 on 2025-03-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0076_alter_elementecartitem_element_nr'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='dichtungstypen',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artikel',
            name='lieferanten_artikelnummern',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
