# Generated by Django 4.1.4 on 2025-03-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0076_artikel_dichtungstypen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementecartitem',
            name='element_nr',
            field=models.CharField(max_length=100, verbose_name='Element-Nr.'),
        ),
    ]
