# Generated by Django 5.1.6 on 2025-03-19 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0077_artikel_dichtungstypen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementecartitem',
            name='element_nr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elemente_cart_items', to='store.elemente'),
        ),
    ]
