# Generated by Django 5.1.6 on 2025-03-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0078_alter_elementecartitem_element_nr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementecartitem',
            name='element_nr',
            field=models.CharField(max_length=255, verbose_name='Element-Nr.'),
        ),
    ]
