# Generated by Django 5.1.6 on 2025-03-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0080_alter_elementecartitem_element_nr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementecartitem',
            name='element_nr',
            field=models.IntegerField(blank=True, max_length=255, null=True, verbose_name='Element-Nr.'),
        ),
    ]
